languageCode = "zh-tw"
languageName = "繁體中文"
weight = 1
title = "貝坦betan"

[params]
  displayName = "繁體中文"
  isoCode = "zh-tw"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/logo.png"
  # secondaryLogo = "img/logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

 [author]
   name = "貝坦betan"
   image = "img/betan_logo.gif"
   headline = "窩是貝坦"
   bio = "窩是貝坦"
   links = [
     { discord = "https://discordapp.com/users/414682490125418496" },
     { github = "https://github.com/Betan423" },
     { instagram = "https://instagram.com/gul_dx600" },
   ]
